// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-my-sessions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-my-sessions.ts
var list_my_sessions_default = defineTool({
  name: "list_my_sessions",
  title: "\uB0B4 \uC751\uC2DC \uC138\uC158 \uBAA9\uB85D",
  description: "\uB85C\uADF8\uC778\uD55C \uC0AC\uC6A9\uC790 \uBCF8\uC778\uC774 \uC751\uC2DC\uD55C \uC2DC\uD5D8 \uC138\uC158 \uBAA9\uB85D\uC744 \uBC18\uD658\uD569\uB2C8\uB2E4 (\uC0C1\uD0DC, \uC810\uC218, \uC2DC\uD5D8 \uC815\uBCF4 \uD3EC\uD568).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("\uBC18\uD658\uD560 \uC138\uC158 \uCD5C\uB300 \uAC1C\uC218 (\uAE30\uBCF8 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\uB85C\uADF8\uC778\uC774 \uD544\uC694\uD569\uB2C8\uB2E4." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("exam_sessions").select("id, exam_id, status, score_total, start_time, submit_time, exams(title, grade, exam_date)").eq("applicant_id", ctx.getUserId()).order("start_time", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: `\uC870\uD68C \uC2E4\uD328: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-certifications.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_certifications_default = defineTool2({
  name: "list_my_certifications",
  title: "\uB0B4 \uC778\uC99D\uC11C \uBAA9\uB85D",
  description: "\uB85C\uADF8\uC778\uD55C \uC0AC\uC6A9\uC790\uAC00 \uCDE8\uB4DD\uD55C AI CAPA \uC778\uC99D\uC11C \uBAA9\uB85D\uC744 \uBC18\uD658\uD569\uB2C8\uB2E4.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\uB85C\uADF8\uC778\uC774 \uD544\uC694\uD569\uB2C8\uB2E4." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("certifications").select("id, cert_number, grade, issued_at, status, exam_id").eq("applicant_id", ctx.getUserId()).order("issued_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: `\uC870\uD68C \uC2E4\uD328: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { certifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-open-exams.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_open_exams_default = defineTool3({
  name: "list_open_exams",
  title: "\uC751\uC2DC \uAC00\uB2A5 \uC2DC\uD5D8 \uBAA9\uB85D",
  description: "\uD604\uC7AC open \uC0C1\uD0DC\uC778 \uC2DC\uD5D8(\uACF5\uAC1C \uC2DC\uD5D8) \uBAA9\uB85D\uC744 \uBC18\uD658\uD569\uB2C8\uB2E4.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("\uBC18\uD658 \uAC1C\uC218 (\uAE30\uBCF8 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\uB85C\uADF8\uC778\uC774 \uD544\uC694\uD569\uB2C8\uB2E4." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("exams").select("id, title, grade, exam_date, duration_minutes, max_participants, status").eq("status", "open").order("exam_date", { ascending: true }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: `\uC870\uD68C \uC2E4\uD328: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { exams: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-session-result.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_session_result_default = defineTool4({
  name: "get_session_result",
  title: "\uC138\uC158 \uCC44\uC810 \uACB0\uACFC \uC870\uD68C",
  description: "\uD2B9\uC815 \uC751\uC2DC \uC138\uC158\uC758 \uCD1D\uC810\xB7\uD569\uACA9\uC5EC\uBD80\xB7\uBB38\uD56D\uBCC4 \uC810\uC218/\uD53C\uB4DC\uBC31\uC744 \uBC18\uD658\uD569\uB2C8\uB2E4. \uBCF8\uC778 \uC138\uC158\uB9CC \uC870\uD68C \uAC00\uB2A5.",
  inputSchema: {
    session_id: z3.string().uuid().describe("\uC870\uD68C\uD560 exam_sessions.id")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\uB85C\uADF8\uC778\uC774 \uD544\uC694\uD569\uB2C8\uB2E4." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: session, error: sErr } = await supabase.from("exam_sessions").select("id, exam_id, status, score_total, start_time, submit_time, applicant_id").eq("id", session_id).maybeSingle();
    if (sErr) return { content: [{ type: "text", text: `\uC138\uC158 \uC870\uD68C \uC2E4\uD328: ${sErr.message}` }], isError: true };
    if (!session) return { content: [{ type: "text", text: "\uC138\uC158\uC744 \uCC3E\uC744 \uC218 \uC5C6\uAC70\uB098 \uC811\uADFC \uAD8C\uD55C\uC774 \uC5C6\uC2B5\uB2C8\uB2E4." }], isError: true };
    const { data: answers, error: aErr } = await supabase.from("answers").select("question_id, score, feedback").eq("session_id", session_id);
    if (aErr) return { content: [{ type: "text", text: `\uB2F5\uC548 \uC870\uD68C \uC2E4\uD328: ${aErr.message}` }], isError: true };
    const result = { session, answers: answers ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eoeiqpgzoyltrawfflhj";
var mcp_default = defineMcp({
  name: "aicapa-mcp",
  title: "AI CAPA MCP",
  version: "0.1.0",
  instructions: "AI CAPA \uC778\uC99D\uD3C9\uAC00 \uD50C\uB7AB\uD3FC\uC758 \uC0AC\uC6A9\uC790 \uB370\uC774\uD130 \uC870\uD68C\uC6A9 MCP \uC11C\uBC84\uC785\uB2C8\uB2E4. \uBCF8\uC778\uC774 \uC751\uC2DC\uD55C \uC2DC\uD5D8 \uC138\uC158, \uC778\uC99D\uC11C, \uCC44\uC810 \uACB0\uACFC\uB97C \uC870\uD68C\uD558\uAC70\uB098 \uD604\uC7AC \uC751\uC2DC \uAC00\uB2A5\uD55C \uC2DC\uD5D8 \uBAA9\uB85D\uC744 \uD655\uC778\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_open_exams_default, list_my_sessions_default, list_my_certifications_default, get_session_result_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
